# Generated by Django 5.1.7 on 2025-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_price1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'الدفع عند الاستلام'), ('online', 'دفع إلكتروني')], default='cash', max_length=10),
        ),
    ]
