# Generated by Django 5.1.7 on 2025-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'الدفع عند الاستلام'), ('online', 'دفع إلكتروني')], default='cash', max_length=100),
        ),
    ]
